name: ${DOCKER_APP_NAME:-react-router-starter}

services:
  react-router-service:
    container_name: ${DOCKER_APP_NAME:-react-router-starter}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        APP_NAME: ${APP_NAME}
        BASE_URL: ${BASE_URL}
        SYSTEM_MAIL_SENDER: ${SYSTEM_MAIL_SENDER}
        MAILER_HOST: ${MAILER_HOST}
        MAILER_PORT: ${MAILER_PORT}
        MAILER_USER: ${MAILER_USER}
        MAILER_PASS: ${MAILER_PASS}
        ALLOW_INDEXING: ${ALLOW_INDEXING}
        MATOMO_URL: ${MATOMO_URL}
        MATOMO_SITE_ID: ${MATOMO_SITE_ID}
        SESSION_SECRETS: ${SESSION_SECRETS}
        HONEYPOT_SECRETS: ${HONEYPOT_SECRETS}
        CSRF_SECRETS: ${CSRF_SECRETS}
        MESSAGE_SECRETS: ${MESSAGE_SECRETS}
    expose:
      - 3000
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - react-router-starter-network

  nginx-service:
    image: nginx:1.28.2
    container_name: ${DOCKER_APP_NAME:-react-router-starter}-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/gdpr-safe-logs.conf:/etc/nginx/conf.d/00-gdpr-safe-logs.conf:ro
      - ./nginx/http-connection-upgrade-map.conf:/etc/nginx/conf.d/01-http-connection-upgrade-map.conf:ro
      - ${SSL_DOCKER_MOUNT:-./nginx/dev/ssl:/etc/letsencrypt:ro}
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    networks:
      - react-router-starter-network

networks:
  react-router-starter-network:
    external: true