map $remote_addr $masked_ip {
    # IPv4: mask last octet
    ~(?P<ip>\d+\.\d+\.\d+)\.    $ip.0;
    # IPv6: mask after second group
    ~(?P<ip>[^:]+:[^:]+):       $ip::;
    default                      0.0.0.0;
}

# Note: If you want to stay GDPR compliant, make sure to mask sensitive user data from the url (url params, search params) and referer once its implemented.
# F.e. tokens, usernames, etc...
log_format gdpr_safe '$masked_ip - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent '
                     '"$http_user_agent"';